"""Model confidence page - read-only view to help the chemist trust (or
distrust) a recommendation.

Three sections:
  1. Dataset coverage (how many similar experiments are on file).
  2. Recent calibration (latest bo_calibration_*.png + plain-English summary).
  3. Top features driving recent recommendations (latest SHAP CSV).
"""

from __future__ import annotations

import os
import sys
from datetime import datetime

# Path bootstrap
_PROJECT_ROOT = os.path.dirname(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
if _PROJECT_ROOT not in sys.path:
    sys.path.insert(0, _PROJECT_ROOT)
os.chdir(_PROJECT_ROOT)

import pandas as pd  # noqa: E402
import streamlit as st  # noqa: E402

from app.services.status import (DATA_FILE, DOCS_DIR, dataset_summary,
                                  list_calibration_plots,
                                  shap_csv_index)  # noqa: E402
from app.ui.components import page_header  # noqa: E402


def _data_mtime() -> float:
    """Last-modified time of the experiment Excel, or 0 if missing."""
    try:
        return os.path.getmtime(DATA_FILE)
    except OSError:
        return 0.0


def _freshness(path: str) -> tuple[str, bool]:
    """Return (human-readable generated-at caption, is_stale) for *path*.

    A plot is considered stale if the experiment Excel has been modified
    since the plot was written - i.e. there are newer experiments that
    this plot does not yet reflect.
    """
    try:
        plot_mtime = os.path.getmtime(path)
    except OSError:
        return ("", False)
    generated = datetime.fromtimestamp(plot_mtime).strftime("%Y-%m-%d %H:%M")
    is_stale = plot_mtime < _data_mtime()
    return (generated, is_stale)


def _show_freshness(path: str, *, regen_hint: str) -> None:
    """Render a generated-at caption and an amber staleness warning.

    ``regen_hint`` is the short sentence telling the user which page /
    button regenerates the artifact (different for calibration vs
    training-pipeline plots).
    """
    generated, is_stale = _freshness(path)
    if generated:
        st.caption(f"Generated: {generated}")
    if is_stale:
        st.warning(
            f"New experiments have been recorded since this plot was "
            f"generated. {regen_hint}"
        )

st.set_page_config(page_title="Model Confidence \u00b7 COMPASS",
                   layout="wide")

page_header(
    "Model confidence",
    caption="Inspect how trustworthy the surrogate is for your target chemistry.",
)

# -- Global freshness banner ---
# Different plot types are regenerated by different actions:
#   - roc_prc + learning_curves   → only the **Retrain Model** pipeline
#                                    writes these.
#   - bo_calibration_*.png        → refreshed automatically at the end of
#                                    every retrain (quarterly workflow and
#                                    in-app Retrain / Update model), and also
#                                    written by **BO Tools → Simulate**.
#                                    Running a recommendation does NOT
#                                    refresh them.
# List which plot is stale and pair it with the specific action that
# regenerates it.
_RETRAIN_PLOTS = [
    ("roc_prc_comparison.png",   "ROC / PRC comparison"),
    ("learning_curves_qwk.png",  "Learning curves"),
]
_retrain_stale: list[tuple[str, str]] = []
for fname, friendly in _RETRAIN_PLOTS:
    p = os.path.join(_PROJECT_ROOT, fname)
    if os.path.exists(p) and _freshness(p)[1]:
        _retrain_stale.append((fname, friendly))

_cal_plots = list_calibration_plots()
_cal_stale = bool(_cal_plots) and _freshness(_cal_plots[0])[1]

if _retrain_stale or _cal_stale:
    msg_parts: list[str] = []
    if _retrain_stale:
        stale_list = ", ".join(f"`{fname}` ({friendly})"
                                for fname, friendly in _retrain_stale)
        msg_parts.append(
            f"{stale_list} predate the latest experiment data. "
            "Refresh these by opening **Retrain Model** and running "
            "*Retrain model* - running BO recommend or BO simulate does "
            "**not** regenerate them."
        )
    if _cal_stale:
        msg_parts.append(
            f"The latest BO calibration plot "
            f"(`{os.path.basename(_cal_plots[0])}`) predates the latest "
            "experiment data. Calibration is refreshed automatically by "
            "every retrain - run **Retrain Model → Update model**, or run "
            "**BO Tools → Simulate** for one specific surrogate / "
            "acquisition."
        )
    st.warning("**Some plots are out of date.**\n\n- " + "\n- ".join(msg_parts))

# -- Section 1: dataset coverage ---
st.subheader("Dataset coverage")
ds = dataset_summary()
st.write(
    f"There are **{ds.n_experiments:,}** experiments in the dataset"

)
st.caption(
    "Per-target neighbour counts are computed during a recommendation run. "
    "Open the **Recommend** page and provide your target SMILES to see "
    "how many similar experiments the model has to learn from."
)

st.divider()

# -- Section 2: recent calibration ---
st.subheader("Recent calibration")
plots = list_calibration_plots()
if not plots:
    st.info("No calibration plots have been generated yet. Run a BO "
            "simulation from the **BO Tools** page to produce one.")
else:
    # Let the user pick which calibration plot to view (one per run).
    # `list_calibration_plots` already sorts newest first. Default
    # selection prefers the newest lfbo_ssl plot (matches the project's
    # default acquisition function) and only falls back to the newest of
    # any kind if no lfbo_ssl calibration has been generated yet.
    labels = [os.path.basename(p) for p in plots]
    _default_idx = next(
        (i for i, lbl in enumerate(labels) if "lfbo_ssl" in lbl.lower()),
        0,
    )
    pick_label = st.selectbox(
        "Calibration run",
        options=labels,
        index=_default_idx,
        help="Each BO simulation writes its own calibration plot under "
             "`docs/bo_calibration_<acq>_<surrogate>.png`. Defaults to "
             "the most recent **lfbo_ssl** run (the project's default "
             "acquisition); falls back to the most recent run of any "
             "acquisition if no lfbo_ssl calibration exists yet.",
    )
    if _default_idx == 0 and not any("lfbo_ssl" in lbl.lower() for lbl in labels):
        st.info(
            "No `lfbo_ssl` calibration plot has been generated yet. Run "
            "**BO Tools → Simulate** with acquisition = `lfbo_ssl` to "
            "produce one. Showing the most recent calibration from "
            "another acquisition in the meantime.",
            icon=":material/info:",
        )
    plot = next(p for p, lbl in zip(plots, labels) if lbl == pick_label)
    st.image(plot, caption=pick_label, width="stretch")
    _show_freshness(
        plot,
        regen_hint="Calibration refreshes automatically with every retrain "
                   "(quarterly or **Retrain Model → Update model**); to "
                   "refresh just this surrogate now, run **BO Tools → "
                   "Simulate**.",
    )
    st.caption(
        "Each point on the calibration curve compares predicted uncertainty "
        "against actual prediction error. Closer to the diagonal means the "
        "model's confidence intervals are honest."
    )

st.divider()

# -- Section 3: ROC / PRC pipeline comparison ---
st.subheader("ROC and PRC pipeline comparison")
roc_prc_png = os.path.join(_PROJECT_ROOT, "roc_prc_comparison.png")
roc_prc_csv = os.path.join(_PROJECT_ROOT, "roc_prc_auc_summary.csv")

if not os.path.exists(roc_prc_png):
    st.info("No ROC/PRC comparison plot found. Open the **Retrain Model** "
            "page and click *Retrain model* to generate "
            "`roc_prc_comparison.png`.")
else:
    st.image(roc_prc_png, caption="roc_prc_comparison.png",
             width="stretch")
    _show_freshness(
        roc_prc_png,
        regen_hint="Open **Retrain Model** and run *Retrain model* "
                   "to refresh this plot.",
    )
    st.caption(
        "Each curve is one surrogate pipeline scored on the held-out set. "
        "**ROC** plots true-positive vs false-positive rate as the decision "
        "threshold sweeps. Higher AUC means better ranking. This is not a good measure of surrogate. **PRC** "
        "plots precision vs recall. It is the more honest view when "
        "crystalline hits are rare (the dataset prevalence of crystalline materia is shown for "
        "reference)."
    )

    if os.path.exists(roc_prc_csv):
        try:
            auc_df = pd.read_csv(roc_prc_csv)
            # Round the float columns so the table is readable.
            for col in ("roc_auc", "average_precision", "prevalence"):
                if col in auc_df.columns:
                    auc_df[col] = auc_df[col].astype(float).round(3)
            # Sort so the strongest pipeline is at the top.
            sort_col = ("average_precision" if "average_precision" in auc_df.columns
                        else "roc_auc" if "roc_auc" in auc_df.columns
                        else None)
            if sort_col is not None:
                auc_df = auc_df.sort_values(sort_col, ascending=False)
            st.dataframe(auc_df, width="stretch", hide_index=True)
        except Exception as exc:
            st.warning(f"Could not parse roc_prc_auc_summary.csv: {exc}")

st.divider()

# -- Section 4: learning curves (QWK) ---
st.subheader("Learning Curves (Quadratic-Weighted Kappa)")
lc_png = os.path.join(_PROJECT_ROOT, "learning_curves_qwk.png")
lc_csv = os.path.join(_PROJECT_ROOT, "learning_curve_summary_qwk.csv")

if not os.path.exists(lc_png):
    st.info("No learning-curve plot found. Open the **Retrain Model** "
            "page and click *Retrain model* to generate "
            "`learning_curves_qwk.png`.")
else:
    st.image(lc_png, caption="learning_curves_qwk.png",
             width="stretch")
    _show_freshness(
        lc_png,
        regen_hint="Open **Retrain Model** and run *Retrain model* "
                   "to refresh this plot.",
    )
    st.caption(
        "How performance scales with training-set size, scored by "
        "quadratic-weighted kappa (1.0 = perfect, 0.0 = random). The gap "
        "between the train and validation curves is the **generalization "
        "gap**. A wide gap means the model is memorising rather than "
        "learning."
    )

    if os.path.exists(lc_csv):
        try:
            lc_df = pd.read_csv(lc_csv)
            for col in ("train_mean", "train_std", "val_mean", "val_std",
                        "generalization_gap"):
                if col in lc_df.columns:
                    lc_df[col] = lc_df[col].astype(float).round(3)
            with st.expander("Per-pipeline learning-curve table"):
                st.dataframe(lc_df, width="stretch", hide_index=True)
        except Exception as exc:
            st.warning(f"Could not parse learning_curve_summary_qwk.csv: {exc}")

st.divider()

# -- Section 5: top features driving recent recommendations ---
st.subheader("SHAP Analysis")
shap_entries = shap_csv_index()
if not shap_entries:
    st.info("No SHAP importance CSVs were found. Open the **Retrain "
            "Model** page and run *Full retune* to generate them.")
else:
    # Show one entry per (model_family, feature_block) - keeping only the
    # most-recent CSV for each pipeline and labeling it by feature block
    # (MI only / CL + MI / CL only). Older threshold_0 / threshold_1
    # variants of the same pipeline are no longer offered as separate
    # picks; they were confusing duplicates of the aggregated view.
    labels = [e.label for e in shap_entries]
    pick = st.selectbox(
        "Pipeline",
        options=labels,
        index=0,
        help="Each entry is one trained pipeline (model family × feature "
             "block). The most-recent SHAP CSV for that pipeline is "
             "shown - older threshold-specific variants are hidden to "
             "keep this list short.",
    )
    chosen = next(e for e in shap_entries if e.label == pick)
    st.caption(
        f"Source file: `{os.path.basename(chosen.path)}` · "
        f"model family: **{chosen.model_family}** · "
        f"feature block: **{chosen.feature_block}**"
    )
    _show_freshness(
        chosen.path,
        regen_hint="Open **Retrain Model** and run *Full retune* "
                   "to refresh SHAP importances.",
    )
    try:
        df_shap = pd.read_csv(chosen.path)
        # Detect the most likely "importance" column.
        importance_col = next(
            (c for c in ["mean_abs_shap", "importance", "shap_value", "value"]
             if c in df_shap.columns),
            df_shap.columns[-1],
        )
        feature_col = next(
            (c for c in ["feature", "feature_name", "name"]
             if c in df_shap.columns),
            df_shap.columns[0],
        )
        top = (df_shap[[feature_col, importance_col]]
               .dropna()
               .sort_values(importance_col, ascending=False)
               .head(15))
        st.bar_chart(top.set_index(feature_col), width="stretch")
    except Exception as exc:
        st.warning(f"Could not parse {os.path.basename(chosen.path)}: {exc}")
        st.dataframe(pd.read_csv(chosen.path).head(20))

st.divider()
st.caption(f"Plots and CSVs are read from `{os.path.relpath(DOCS_DIR, _PROJECT_ROOT)}/` "
           "and the project root.")
